server:
  port: 8080

spring:
  application:
    name: discovery

  cloud:
    config:
      enabled: false   # Config Server 체크 비활성화

    gateway:
      discovery:
        locator:
          enabled: true                 # Eureka 서비스 자동 탐색
          lower-case-service-id: true   # 소문자 경로 허용 (/user-service)
      routes:
        - id: user-service
          uri: lb://user-service        # LoadBalancer 통해 user-service로 연결
          predicates:
            - Path=/user-service/**
          filters:
            - StripPrefix=1

eureka:
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:discovery-server}
    prefer-ip-address: false
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true


