bootJar.enabled = true
jar.enabled = false

dependencies {
	// Gateway는 WebFlux(Reactive)를 사용하므로 spring-boot-starter-web 제거
	implementation 'org.springframework.cloud:spring-cloud-starter-gateway'
	implementation 'org.springframework.cloud:spring-cloud-starter-netflix-eureka-client'
	implementation 'org.springframework.cloud:spring-cloud-starter-config'
	developmentOnly 'org.springframework.boot:spring-boot-devtools'
}
